name: Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      - name: Free Port 3500
        run: |
          fuser -k 3500/tcp || true

      - name: Start Spring Boot App
        run: |
          nohup java -jar target/*.jar --server.port=3500 > app.log 2>&1 &
          sleep 15

          echo "===== Application Log ====="
          cat app.log

          curl --fail http://localhost:3500 || exit 1
